name: fast_immutable_collections_benchmarks
description: An isolated package for benchmarking the `fast_immutable_collections` package.
publish_to: "none"
version: 0.0.1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  benchmark_harness: ^2.0.0
  built_collection: ^5.1.1
  collection: ^1.17.0
  fast_immutable_collections:
    path: ../../
  kt_dart: ^0.10.0
  meta: ^1.8.0
  path: ^1.8.0


dev_dependencies:
  lint: ^2.0.1
  test: ^1.17.12
