name: json_serializable_e2e_test
description: e2e tests for fic/json_serializable

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  fast_immutable_collections:
    path: ../
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lint: ^2.0.1
  test: ^1.17.12

publish_to: none

